### ISSUE TITLE
ImportError: cannot import name WebConfig

### ISSUE THREAD

**Issue by daimon99** [endsh/chiki#1]
```
# chiki https://github.com/endsh/cookiecutter-chiki.git
# python manage.py
```

报错：

```
  File "/home/pyer/project/chikiTest/chikiTest/admin/__init__.py", line 7, in <module>
    from chikiTest.config import BaseConfig, WebConfig
ImportError: cannot import name WebConfig
```

检查chikiTest.config，里面没有WebConfig的定义。chikiTest.config的文件内容如下：

```
# coding: utf-8
import os


class BaseConfig(object):
    """ 基础配置 """

    # 目录, i18n
    ROOT_FOLDER = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    DATA_FOLDER = os.path.join(ROOT_FOLDER, 'data')
    DOC_FOLDER = os.path.join(ROOT_FOLDER, 'docs')
    LOG_FOLDER = os.path.join(ROOT_FOLDER, 'logs')
    STATIC_FOLDER = os.path.join(ROOT_FOLDER, 'media')
    TEMPLATE_FOLDER = os.path.join(ROOT_FOLDER, 'templates')
    BABEL_DEFAULT_LOCALE = 'zh_CN'
    CHANGE_400_TO_200 = True

    # Secret Key
    SECRET_KEY = 'SECRET KEY'
    PASSWORD_SECRET = 'PASSWORD SECRET'
    WTF_CSRF_SECRET_KEY = 'WTF CSRF SECRET KEY'

    MONGODB_SETTINGS = dict(host='127.0.0.1', port=27017, db='chikiTest')

    UPLOADS = dict(
        type='local',
        link='/uploads/%s',
        path=os.path.join(DATA_FOLDER, 'uploads'),
    )

    # 版本，网站名称等
    VERSION = '0.1.0'
    SITE_NAME = u'chikiTest'

class AdminConfig(BaseConfig):
    """ 后台管理通用配置 """

    PORT = 5000
    ENVVAR = 'CHIKITEST_ADMIN'
    SESSION_COOKIE_NAME = 'chikiTest.admin'
    STATIC_FOLDER = os.path.join(BaseConfig.STATIC_FOLDER, 'admin')
    RELEASE_STATIC_FOLDER = os.path.join(BaseConfig.STATIC_FOLDER, 'admin/dist')
    TEMPLATE_FOLDER = os.path.join(BaseConfig.TEMPLATE_FOLDER, 'admin')

    INDEX_REDIRECT = '/admin/'

    # 后台管理员帐号密码
    ADMIN_USERNAME = 'admin'
    ADMIN_PASSWORD = ''
```

**Comment by endsh** [comment]
chiki https://github.com/endsh/cookiecutter-chiki.git -a -w

**Comment by Yaoxin** [comment]
>>> from flask.ext import admin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Pure/.virtualenvs/test/lib/python2.7/site-packages/flask/exthook.py", line 87, in load_module
    raise ImportError('No module named %s' % fullname)
ImportError: No module named flask.ext.admin

**Comment by endsh** [comment]
pip install flask-admin
建议，flask-admin先在github上clone后，用python setup.py install安装，因为这样才能支持i18n
